version: '3'
services:
   mydb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: admin

   myweb:
     image: httpd
     ports:
      - 80:80
     links: 
      - mydb:mysql
        
   myphp:
    image: php:7.4-fpm-alpine
    ports:
     - 8080:80
    links:
     - mydb:mysql
     - myweb:myphp
   
